### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by AlexMili** [torch/image#107]
I'm trying to loop over a table of images to re-scale, after a few moments my RAM is almost full.
I didn't find any close() function to close my image when I saved it on the disk.

Here is my code :
```lua
function resize_images(df, width, height)
    n_train = count_training_files(df)
    
    j = 0
    for i = 1, df.n_rows do
        if file_exists('./imgs/'..df.dataset['Image'][i]) == true then
            new_image = image.loadJPG('./imgs/'..df.dataset['Image'][i])
            img = image.scale(new_image, width, height)
            image.save('./data/'..df.dataset['Image'][i], img)
            img = nil
            new_image = nil
            j = j + 1
            print(df.dataset['Image'][i]..' resized ('.. n_train-j ..' left)')
        end
    end
end
```

Is there a better way or am I missing something ?

**Comment by deltheil** [comment]
The garbage collector is not aware of the corresponding allocated memory so you can 1/ manually call `collectgarbage()` at the end of your loop (doing that every N iterations should be enough) or 2/ (better) use `torch.setheaptracking(true)` at the beginning of your script (see torch/torch7#280 and torch/torch7#324 for more details).

**Comment by AlexMili** [comment]
`torch.setheaptracking(true)` fixed my problem. Thanks !
