### ISSUE TITLE
image.rotate can't have dst and src pointing to the same memory

### ISSUE THREAD

**Issue by rotmanmi** [torch/image#108]
Hi,

If dst = src, then the image rotation fails, for instance:

require 'image'
theta = 1
a = image.lena()
image.rotate(a,a,theta)
itorch.image(a)

Best,

Michael.

**Comment by soumith** [comment]
yes indeed, we've add an assertion that gives an error if the source and destination are the same:
https://github.com/torch/image/blob/master/generic/image.c#L405
