### ISSUE TITLE
crop(src, x1, y1) broken

### ISSUE THREAD

**Issue by andresy** [torch/image#113]
what is supposed to do crop(src, x1, y1)? it is not working at this time. i can fix it (i would picked that the missing x2, y2 are the right bottom coordinates of the src image), but i need to know for sure what was the intended behavior :smile: .

also, crop(dst, src, x1, y1) is cheesy (well, compared to what the documentation says!): it uses the dst size to compute the missing coordinates (instead of using dst only to put the result, as advertised).

can we choose a consistent behavior between all these crop alternatives?

**Comment by soumith** [comment]
I guess you fixed this already. Thanks. I think no one has used it without x2, y2 because it errored :) #baddocs
