### ISSUE TITLE
issue with image.display()

### ISSUE THREAD

**Issue by rahulr88** [torch/image#127]
Hi,

I am using Torch7 with Ubuntu 14.04 and faced an issue with the function

image.display(im) -- image is loaded to the variable im.

The error I am getting is this

/home/rahul/torch/install/share/lua/5.1/trepl/init.lua:383: module 'qt' not found:No LuaRocks module found for qt
        no field package.preload['qt']
        no file '/home/admin/.luarocks/share/lua/5.1/qt.lua'
        no file '/home/admin/.luarocks/share/lua/5.1/qt/init.lua'
        no file '/home/rahul/torch/install/share/lua/5.1/qt.lua'
        no file '/home/rahul/torch/install/share/lua/5.1/qt/init.lua'
        no file './qt.lua'
        no file '/home/rahul/torch/install/share/luajit-2.1.0-alpha/qt.lua'
        no file '/usr/local/share/lua/5.1/qt.lua'
        no file '/usr/local/share/lua/5.1/qt/init.lua'
        no file '/home/rahul/.luarocks/share/lua/5.1/qt.lua'
        no file '/home/rahul/.luarocks/share/lua/5.1/qt/init.lua'
        no file '/home/admin/.luarocks/lib/lua/5.1/qt.so'
        no file '/home/rahul/torch/install/lib/lua/5.1/qt.so'
        no file './qt.so'
        no file '/usr/local/lib/lua/5.1/qt.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/rahul/.luarocks/lib/lua/5.1/qt.so'
stack traceback:
        [C]: in function 'error'
        /home/rahul/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
        /home/rahul/torch/install/share/lua/5.1/image/init.lua:1334: in function 'display'
        [string "_RESULT={image.display(image.lena())}"]:1: in main chunk
        [C]: in function 'xpcall'
        /home/rahul/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
        ...ahul/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406670

I tried the following

1. Followed (https://groups.google.com/forum/#!searchin/torch7/image.display/torch7/kMP9vYyRwGg/8-EhC_QI84EJ ) and tried qlua -e "require('trepl')()" and in the prompt th> I was able to display an image after loading it.
2. Similarly, I tried qlua myscript.lua (It has the code image.display(im)) and it works - But quite slow. I tried disabling the code to display the image. Still slow.
3. Ran th myscript.lua and I get the above error. I have seen in one post by @soumith  about a similar issue (https://github.com/torch/qtlua/issues/7) and tried changing the package.path and package.cpath to the ones shown at the output of the qlua interpreter. Still when I run th main.lua, it shows the same error.

May be a silly newbie problem. Any help is much appreciated. Thanks

Here is a screenshot of the issue. I have also displayed the package.path and package.cpath on both qlua and th

![lua](https://cloud.githubusercontent.com/assets/5535285/11210202/55161ae0-8d61-11e5-8a2d-08ea3c2bd50c.JPG)

Rahul R

**Comment by soumith** [comment]
I guess Francisco replied to this on the forums.

**Comment by rahulr88** [comment]
Yes he did. Thanks a lot

**Comment by abhishekarya286** [comment]
@rahulr88, How did you solve this? I'm having the similar issue.

**Comment by sheikirfanbasha** [comment]
I solved it by using the methods image.toDisplayTensor followed by image.save which doesn't depend on qtlua package.
Sample snippet:
`ou=image.toDisplayTensor{input=n.output, padding=2, zoom=4};
  image.save('fname.png', ou)`

**Comment by abarya** [comment]
Thanks sheik for your help.
