### ISSUE TITLE
Problem on installing 'image' in ubuntu

### ISSUE THREAD

**Issue by mlakhal** [torch/image#153]
I am having trouble on installing 'image' package, I have tried to remove and then re-install 'libjpeg-dev'. But, I can't get the package installed on my system. I have this error message when typing `'luajit -limage -e "image.test()"'`.

`luajit: /usr/local/share/lua/5.1/image/test.lua:1: attempt to call field 'TestSuite' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/image/test.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/image/init.lua:48: in main chunk
	[C]: at 0x00464010
	[C]: at 0x00406260
`

**Comment by soumith** [comment]
upgrade your torch package via: luarocks install torch 
After that you'll have no issues.
