### ISSUE TITLE
Installed image using luarocks but fails test

### ISSUE THREAD

**Issue by prashanth-srinivasan** [torch/image#158]
Hi, 

I installed the image package using 'luarocks install image' . 
However, when I try  ' luajit -limage -e "image.test()"  '
it fails with the error below : 

luajit: ...h/software/DL/torch/install/share/lua/5.1/image/init.lua:37: module 'sys.fpath' not found:
	no field package.preload['sys.fpath']
stack traceback:
	[C]: in function 'require'
	...h/software/DL/torch/install/share/lua/5.1/image/init.lua:37: in main chunk
	[C]: at 0x00465040
	[C]: at 0x00405d70

The error mainly says that it couldn't find the image library in the fpath.lua or init.lua files of multiple directories. 

Any suggestions on how to get this working?

**Comment by deltheil** [comment]
Upgrade [sys](https://github.com/torch/sys) via `luarocks install sys` (see #157).

**Comment by prashanth-srinivasan** [comment]
Thanks @deltheil  ! It worked. I was surprised since the other packages (nn, optim, xlua etc.) were working fine in my programs while require 'image' threw the error.
