### ISSUE TITLE
License: please remove non-free lena image

### ISSUE THREAD

**Issue by CDLuminate** [torch/image#172]
As a reminder of discussion at https://github.com/torch/nn/issues/854

`Jelly bean` seems to be a good alternative, would you like to also reaplace `image.lena()` function
with `image.jellybean()` like this:

```lua
function image.lena()
   print('dear user due to license issue the lena image is removed and image.lena() is deprecated, use jellybean image instead')
   return image.jellybean()
end
```

**Comment by soumith** [comment]
fixed via https://github.com/torch/image/commit/797fcb101b76c9b329b3ee83349b0f6adeacac94

following Matplotlib and Pillow to add grace hopper instead
https://github.com/matplotlib/matplotlib/pull/1581
