### ISSUE TITLE
Unexpected Tensor type - affinetransform 

### ISSUE THREAD

**Issue by pinhasnis** [torch/image#187]
i'm trying to use affinetransform

-- code

require 'torch'
require 'image'
torch.setdefaulttensortype('torch.FloatTensor')

local im = image.lena()
local matrix = torch.Tensor({{1,0.5},{0,1}})
local dst = torch.zeros(im:size())
local im2 = image.affinetransform(dst,im,matrix,'bilinear',torch.Tensor({0,0}),'pad',0)

-- end code

but i'm getting the following error:

/Users/pinhas/torch/install/share/lua/5.1/image/init.lua:1084: bad argument #
3 to 'warp' (torch.FloatTensor expected, got torch.DoubleTensor)
stack traceback:
        [C]: in function 'warp'
        /Users/pinhas/torch/install/share/lua/5.1/image/init.lua:1084: in function 'affinetransform'

i think that the fix should be replacing lines 1068 and 1075 inside init.lua with:
local grid_xy = torch.Tensor()   --line 1068
field = (grid_xy - field:reshape( 2, height, width ))  --line 1075

**Comment by chsasank** [comment]
Hi, 

Sorry for the late reply. I originally authored affinetransform. I have raised a PR fixing the issue.
