### ISSUE TITLE
Application with multiple threads each importing image module gets hung

### ISSUE THREAD

**Issue by npanpaliya** [torch/image#195]
Hi,

We have built torch on ppc64le. And while testing it, we found a problem wherein threads get hung if we have a thread pool containing higher number of threads say 16 (at times, even with 8) and if all of them are importing 'image'.

Here is our test case -

```
local Threads = require 'threads'
nthreads = 16
Threads.serialization('threads.sharedserialize')
thrds = Threads(nthreads,
         function()  require 'image' end
      );
thrds:synchronize()
print "Done"

```
Some of my observations -
- This test works just fine on x86_86 with the latest torch distro repo
- For ppc, we have a bit older code on top of which ppc specific changes are present. With this setup, this test gets hung. 
- I also tried updating torch submodules like threads, images on my ppc setup but no luck
- Instead of 'image', if I make threads import other modules like torch or sundown from torch, then those cases work. This could be just a fluke, but I'm not really sure.
- Debugging using gdb shows that some threads are sitting in __pthread_cond_wait and some in __lll_lock_wait, creating a deadlock. 

Is importing 'image' a resource intensive operation? Has anyone seen such problem earlier on any other platform?
Any help would be greatly appreciated.

**Comment by npanpaliya** [comment]
This issue may not be directly due to image module. But if I get an idea about what this module is doing intensively which is leading to this hang problem, I may be able to nail down the problem further. Forgot to mention one point - the glibc version on my ppc setup is 2.23-0ubuntu3 and on x86_64 is 2.19-0ubuntu6.

**Comment by npanpaliya** [comment]
We got this issue fixed by building torch using the latest Advanced Toolchain to 10.0 which has gcc 6.2.1 and glibc 2.24.

**Comment by nagadomi** [comment]
I confirmed that this issue is fixed, also in my environment.
```
local threads = require 'threads'
local nthread = 32

local pool = threads.Threads(
   nthread,
   threads.safe(
   function(threadid)
      require 'image'
   end)
)
pool:synchronize()
pool:terminate()
```
`threads.safe` avoids the deadlock problem that is caused by fork() at require() phase.

**Comment by npanpaliya** [comment]
Thanks @nagadomi for this information. I tried updating threads packages and the mentioned test case worked with even 64 threads! Thank you for informing this.
