### ISSUE TITLE
Can't draw Chinese Text

### ISSUE THREAD

**Issue by zhang11wu4** [torch/image#197]
When I want to draw chinese characters with function drawtext, output  unreadable code on the image, who could help me to fix the error? thanks!

**Comment by soumith** [comment]
hi, only a few characters are supported, i.e. ascii 0 to 55 or so...

**Comment by zhangxiangxiao** [comment]
I drew it by converting unicode to images after building a font dictionary using GNU Unifont.

![screenshot from 2015-12-24 19-47-02](https://cloud.githubusercontent.com/assets/1197560/19445066/e373e5b8-9460-11e6-9d5c-df2b794a5e59.png)
