### ISSUE TITLE
libpng check possible typo

### ISSUE THREAD

**Issue by sshekh** [torch/image#217]
In file [init.lua](https://github.com/torch/image/blob/master/init.lua#L208) function `compressPNG`

```lua
local function compressPNG(tensor)
   if not xlua.require 'libpng' then
      dok.error('libpng package not found, please install libpng',
'image.compressPNG')
```

Shouldn't `libpng` be replaced by `liblua_png`, like it is there in other checks? Current Image build is failing the `luajit -limage -e "image.test()"` test.

**Comment by soumith** [comment]
was fixed in master recently.
