### ISSUE TITLE
[CentOS6.4] libjpeg.so.8 problem

### ISSUE THREAD

**Issue by adamist521** [torch/image#41]
I get the error pasted at bottom when I try to use image library of torch7 due to libjpeg.
I'm using torch7 at CentOS6.4 installed by torch-distro.

I have installed `libjpeg-turbo `, `libjpeg-turbo-devel` by yum but the what I get under `/usr/lib` are only `libjpeg.so`, `libjpeg.so.62` and `libjpeg.so.62.0.0`.
I tried to download `libjpeg.so.8` from web but I couldn't make it. 

Is it possible to use ver.62 as alternate of ver.8 OR do you know a way to install ver.8 of libjpeg on CentOS6.4?

```
In [1]: require 'image'
Out[1]:
true


In [2]: image.load('sample.jpg')
Out[2]:
error loading module 'libjpeg' from file '/home/*******/torch-distro/install/lib/lua/5.1/libjpeg.so':
        libjpeg.so.8: cannot open shared object file: No such file or directory
warning: <libjpeg> could not be loaded (is it installed?)

...******/torch-distro/install/share/lua/5.1/dok/inline.lua:633: <image.loadJPG> libjpeg package not found, please install libjpeg
stack traceback:
        [C]: in function 'error'
        ...******/torch-distro/install/share/lua/5.1/dok/inline.lua:633: in function 'error'
        ...******/torch-distro/install/share/lua/5.1/image/init.lua:137: in function 'loader'
        ...******/torch-distro/install/share/lua/5.1/image/init.lua:275: in function 'f'
        [string "local f = function() return image.load('sampl..."]:2: in main chunk
        [C]: in function 'xpcall'
        ...******/torch-distro/install/share/lua/5.1/itorch/main.lua:194: in function <...******/torch-distro/install/share/lua/5.1/itorch/main.lua:160>
        ...******/torch-distro/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
        ...*****/torch-distro/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
        ...*****/torch-distro/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
        ...*****/torch-distro/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
        ...*****/torch-distro/install/share/lua/5.1/itorch/main.lua:374: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00405330

In [3]:
```

**Comment by julj** [comment]
Same here. I'm trying to run the [getstarted.lua](https://github.com/torch/tutorials/blob/master/1_getstarted/getstarted.lua) script from the tutorial:

`th getstarted.lua`

and I get

```
[julj@xxx tests]$ th test_torch.lua 
basic printing  
10
something
number  
string  
/home/julj/torch/install/share/lua/5.1/trepl/init.lua:319: ...e/julj/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/home/julj/torch/install/lib/lua/5.1/libjpeg.so':
        /home/julj/torch/install/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_src
warning: <libjpeg> could not be loaded (is it installed?)
```

`/home/julj/torch/install/lib/lua/5.1/libjpeg.so` does exist. What am I missing?

**Comment by NorThanapon** [comment]
From my experience, libjpeg-turbo does not work for CentOS 6 user. I installed libjpeg 8d ([instruction](http://archive.linuxfromscratch.org/blfs-museum/snapshot-20121101/blfs-20121102/general/libjpeg.html)) and reinstalled torch. This fixed my problem.

**Comment by Jeongseob** [comment]
@NorThanapon 

I installed the libjpeg-8d, but the problem still exists. I think that I need to link the newly installed libjpeg instead of "torch/install/lib/lua/5.1/libjpeg.so". Could you tell me in more details how to fix the problem?

**Comment by NorThanapon** [comment]
I think this is what I did:

    wget http://www.ijg.org/files/jpegsrc.v8d.tar.gz
    tar -xvf jpegsrc.v8d.tar.gz
    cd jpeg-8d/ 
    sudo ./configure
    sudo make
    sudo make install

Then install Torch (assume you have all the [dependencies](https://raw.githubusercontent.com/torch/ezinstall/master/install-deps)

    git clone https://github.com/torch/distro.git ~/torch --recursive
    cd ~/torch
    ./install.sh

I did not use ``sudo`` to install torch because libjpeg-8d is installed in ``/usr/local/lib``.

**Comment by Jeongseob** [comment]
@NorThanapon 
Thanks! Actually, I remove libjpeg-turbo-devel and build the jpengsrc.v8d.tar.gz. After that, I completely reinstall Torch. It works!

**Comment by gongxijun** [comment]
maybe you can try:
`yum install libjpeg-devel`
and excute
`luarocks install image`
