### ISSUE TITLE
image.toDisplayTensor broken for ByteTensors

### ISSUE THREAD

**Issue by jucor** [torch/image#49]
Hi all

Commit 3bc649ac0258936dfc67e5de8320faed649b6bf8 in October 2014 as part of pull-request #36  introduced a bug on `ByteTensor` inputs and changed the in-place/not-in-place contract of `toDisplayTensor`. 

Since then, `image.toDisplayTensor` outputs wrong values when given  a 3-by-H-by-W ByteTensor. 
This is because that commit made some calls `toDisplayTensor` in-place, especially those where the input is a 3-channels RGB image. Whereas before, the input was copied into the `(Double)Tensor` `grid`.

Sine this copy to `Tensor` was removed, the inplace `minmax` operation that is called on the tensor at [line 867](https://github.com/torch/image/blob/3bc649ac0258936dfc67e5de8320faed649b6bf8/init.lua#L867)   tries to renormalize on a `ByteTensor`, and of course does that poorly due to rounding to the nearest integer that occurs in a `ByteTensor`.

**Comment by jucor** [comment]
As a fix, I do not know what you prefer: removing the in-place feature (or making it optional with a flag), which seems cleaner since it re-establishes the good old behaviour, or detecting that we are working on a ByteTensor and copying it to a double (hence not inplace anymore) in these cases?

**Comment by nicholas-leonard** [comment]
Remove the in-place. It shouldn't have been made in-place in the first place.

**Comment by jucor** [comment]
Thanks for the answer @nicholas-leonard. Sounds good to me, I can do that. @koraykv, is that fine with you?

**Comment by jucor** [comment]
Discussed offline with @koraykv, fine with not being in place anymore, I will send a PR.

**Comment by soumith** [comment]
fixed by yourself, thanks!

**Comment by jucor** [comment]
Any time :)
