### ISSUE TITLE
`{v,h}flip` bug

### ISSUE THREAD

**Issue by Atcold** [torch/image#61]
This commit (https://github.com/torch/image/commit/14f20a798102f514369fc22225977ccfe3491ce2) throws an error if the input vector is not contiguous, breaking code.
Before, non contiguous vector were not a problem.
More comments and tests are available at the commit webpage.

@jonathantompson, would you mind patching it up?

**Comment by jonathantompson** [comment]
For now we can change the assert to only throw the non-contiguity error for 2D inputs (hflip and vflip are broken for the 2D case) and ignore the 3D case.  Thanks @Aysegul for pointing this out.

@Atcold  Do you want to post the PR or would you like me to do it?

Here is the broken code snippet for the 2D case:

```lua
require 'image'
input = torch.rand(6,6)
input = input:transpose(1,2)
assert(not input:isContiguous())
err = image.hflip(input) - image.hflip(input:contiguous())
print(err:abs():max())
```

**Comment by Atcold** [comment]
No, please, go ahed. It's your commit. Just mention me, if you don't mind :wink:

**Comment by soumith** [comment]
is this still an issue? if not @Atcold can you close it.

**Comment by Atcold** [comment]
@soumith, it is a back compatibility issue.
The user, now, has to make the input contiguous. I would instead suggest to have the check done internally, in `{v,h}flip`, and issue `:contiguous()` if the input `Tensor` is not.

**Comment by jonathantompson** [comment]
"I thought @jonathantompson would have fixed it himself."

@jonathantompson likes to sleep sometimes :-)

I'm actually OK with requiring the input to be contiguous.  I'm not overly happy when function calls allocate memory on the fly under the hood without me knowing it (i.e. to make the input contiguous).

**Comment by soumith** [comment]
non-issue. user-fixable.
