### ISSUE TITLE
image.display(image.lena()) is not working

### ISSUE THREAD

**Issue by deepakjnath** [torch/image#77]
l = image.lena()
                                                                      [0.0064s]	
th> image.display(l)
...e/deepakjnath/torch/install/share/lua/5.1/trepl/init.lua:363: module 'qt' not found:No LuaRocks module found for qt
	no field package.preload['qt']
	no file '/home/deepakjnath/.luarocks/share/lua/5.1/qt.lua'
	no file '/home/deepakjnath/.luarocks/share/lua/5.1/qt/init.lua'
	no file '/home/deepakjnath/torch/install/share/lua/5.1/qt.lua'
	no file '/home/deepakjnath/torch/install/share/lua/5.1/qt/init.lua'
	no file './qt.lua'
	no file '/home/deepakjnath/torch/install/share/luajit-2.1.0-alpha/qt.lua'
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file '/home/deepakjnath/.luarocks/lib/lua/5.1/qt.so'
	no file '/home/deepakjnath/torch/install/lib/lua/5.1/qt.so'
	no file './qt.so'
	no file '/usr/local/lib/lua/5.1/qt.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...e/deepakjnath/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	...e/deepakjnath/torch/install/share/lua/5.1/image/init.lua:1237: in function 'display'
	[string "_RESULT={image.display(l)}"]:1: in main chunk
	[C]: in function 'xpcall'
	...e/deepakjnath/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...nath/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0003s]	
th>

**Comment by soumith** [comment]
image.display displays stuff using qt, and needs our specially compiled torch interpreter called "qlua".
It should be there by default, in the torch install.
In the terminal, instead of typing:
$ th

type:

$ qlua

to start torch.

**Comment by deepakjnath** [comment]
Thank you ! it worked
