### ISSUE TITLE
Artefacts on image.rotate()

### ISSUE THREAD

**Issue by etrulls** [torch/image#80]
I'm working with small patches and I'm having problems with image.rotate(). Neither the 'simple' nor the 'bilinear' method seem to do what I would expect:

Simple itorch script to rotate a small image:
```lua
require 'image'
side = 25
if true then
   x = image.scale( image.lena(), side )
else
   x = torch.DoubleTensor(3, side, side):fill(1)
   center = torch.floor(side/2)
   x[1][c][c] = 1 x[2][c][c] = 0 x[3][c][c] = 0
end

zoom = 10 -- no zoom with itorch.image?
y = image.rotate(x, math.pi/2, 'simple')
itorch.image( {image.scale(x,side*zoom,'simple'), image.scale(y,side*zoom,'simple')} )

y = image.rotate(x, math.pi/2, 'bilinear')
itorch.image( {image.scale(x,side*zoom,'simple'), image.scale(y,side*zoom,'simple')} )
```
Results, 13x13: https://dl.dropboxusercontent.com/u/34854207/debugging-torch/lena-odd.png
Results, 14x14: https://dl.dropboxusercontent.com/u/34854207/debugging-torch/lena-even.png
(On either, top row: 'simple', bottom row: 'bilinear')

For an odd patch size, the central column/row is duplicated with 'simple', and for 'bilinear' there's a one column/row shift. For an even patch size there's a strange artefact on the central column/row for 'simple' (appears to be shifted? and the "central" pixel is repeated 4 times), and a one-row shift for 'bilinear', plus angle quantization errors (I guess).

Maybe it's easier to see with a toy example:
Results, 13x13: https://dl.dropboxusercontent.com/u/34854207/debugging-torch/toy-odd.png
Results, 14x14: https://dl.dropboxusercontent.com/u/34854207/debugging-torch/toy-even.png

Any ideas?

**Comment by soumith** [comment]
@etrulls I saw #80 and it looks reasonably okay. I forgot to reply to it. I think that's what you get with those interpolation methods right? as in, they are doing what they are supposed to do. Now if you want something nicer, you could try using Lanczos interp for rotations: https://github.com/torch/image/blob/master/test/test_warp.lua#L64

**Comment by soumith** [comment]
I think these are just quantization errors. After calculating the bilinear interp, when it quantize it down to an integer
