### ISSUE TITLE
error after reinstalling Image package: error loading module 'libimage'

### ISSUE THREAD

**Issue by vislab2013** [torch/image#84]
After reinstalling the 'image' package (luarocks install image) i get the following error:

...oiso/Toolkits/torch/install/share/lua/5.1/trepl/init.lua:354: ...oiso/Toolkits/torch/install/share/lua/5.1/trepl/init.lua:354: ...Toolkits/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libimage' from file '/home/coiso/Toolkits/torch/install/lib/lua/5.1/libimage.so':
	/home/coiso/Toolkits/torch/install/lib/lua/5.1/libimage.so: undefined symbol: luaT_setfuncs
stack traceback:
	[C]: in function 'error'
	...oiso/Toolkits/torch/install/share/lua/5.1/trepl/init.lua:354: in function 'f'
	[string "local f = function() return require 'image' e..."]:1: in main chunk
	[C]: in function 'xpcall'
	...oiso/Toolkits/torch/install/share/lua/5.1/trepl/init.lua:620: in function 'repl'
	...kits/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	
                                                   
Tried to install it today on two machines, both gave the same error.

**Comment by soumith** [comment]
Hi,

You have to update your torch. A commit on April 28th added luaT_setfuncs https://github.com/torch/torch7/commit/18fb209ffdf1e42a73a745617bcbf76f0a6136c3

**Comment by vislab2013** [comment]
Updating didn't solved it, but a reinstall of torch did the trick.
