### ISSUE TITLE
Problem with loading libimage.so

### ISSUE THREAD

**Issue by sasadep** [torch/image#85]
Any time that I try to load this rock or any library that depends on this rock, I get the following error:

```
error loading module 'libimage' from file '/home/user/torch/install/lib/lua/5.1/libimage.so':
	/home/user/torch/install/lib/lua/5.1/libimage.so: undefined symbol: luaT_setfuncs
```

This happens when doing:

```
require 'image'
```

or

```
require 'imgraph'
```

or

```
require 'ffmpeg'
```

I have imgraph version 1.0-0 and ffmpeg 1.0-0 installed currently on a computer running Linux Mint 17.1 Rebecca.

**Comment by soumith** [comment]
you'll have to upgrade torch to the latest version.

luarocks install torch

luaT_setfuncs was introduced in a commit on April 29th.
