### ISSUE TITLE
Cannot read 1-bit grayscale png on mac

### ISSUE THREAD

**Issue by edward-zhu** [torch/image#94]
Hi,

I failed loading an 1-bit grayscale png on mac and following error message was shown. 

```
libpng error: invalid after png_start_read_image or png_read_update_info
```

However, if I convert the image to RGB it would work, and if I switch to ubuntu 14.04 with the same grayscale png it also work.

I am using libpng 1.6.18 installed by brew and OS X 10.10.5.

I think the problem would be in `/generic/png.c` at line 99 to 115.

```c
png_read_update_info(png_ptr, info_ptr);

/* get depth */
int depth = 0;
if (color_type == PNG_COLOR_TYPE_RGBA)
  depth = 4;
else if (color_type == PNG_COLOR_TYPE_RGB)
  depth = 3;
else if (color_type == PNG_COLOR_TYPE_GRAY)
  {
    if(bit_depth < 8)
    {
      png_set_expand_gray_1_2_4_to_8(png_ptr);
      png_read_update_info(png_ptr, info_ptr);
    }
    depth = 1;
  }
```

It seems that `png_read_update_info` is called twice, and on ubuntu 14.04 I got following warning: 

```
Ignoring extra png_read_update_info() call; row buffer not reallocated.
```

Shouldn't `png_read_update_info()` be called only once after all `png_set_expand()` things are done?

**Comment by soumith** [comment]
fixed by @edward-zhu in #95
