### ISSUE TITLE
Getting Error while loading png Image in lua

### ISSUE THREAD

**Issue by jbansal** [torch/image#97]
Hi,
I am loading an image using image package in lua.
It is working fine for many png, jpeg images. But for some images it is getting crashed while loading image.

A=image.load(filename )
libpng error: Read Error
/usr/local/torch/install/share/lua/5.1/image/init.lua:136: [read_png_file] Error during read_image
stack traceback:
	[C]: in function 'load'
	/usr/local/torch/install/share/lua/5.1/image/init.lua:136: in function 'loader'
	/usr/local/torch/install/share/lua/5.1/image/init.lua:337: in function 'load'
	[string "A=image.load(filename )"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	

Please let me know how to fix this issue as it is crashing in libpng library
Please find the attached images for which it is crashing.

![152856_294068](https://cloud.githubusercontent.com/assets/8179079/9464262/36526c2a-4b40-11e5-8545-da0791288710.png)

**Comment by deltheil** [comment]
This image sounds corrupted, e.g. with ImageMagick (image renamed foo.png here):

```
$ identify -verbose foo.png
identify: Expected 8192 bytes; found 5714 bytes `foo.png' @ warning/png.c/MagickPNGWarningHandler/1656.
identify: Read Exception `foo.png' @ error/png.c/MagickPNGErrorHandler/1630.
identify: corrupt image `foo.png' @ error/png.c/ReadPNGImage/3959.
```

**Comment by jbansal** [comment]
Hi deltheil,
Thanks for quick feedback. If image is corrupted, then still it should throw some error message or some thing like that. 
But here it is just aborted and then we can not do anything. 
I have thousands images and in that many images like that. 
How to handle such cases in torch.

Regards,
Jitendra Bansal

**Comment by deltheil** [comment]
> If image is corrupted, then still it should throw some error message or some thing like that

The error is reported as a Lua error so you can use [`pcall`](http://www.lua.org/manual/5.2/manual.html#pdf-pcall) to avoid aborting your program (see #58 for more details), e.g.:

```Lua
local ok, img = pcall(image.load, 'foo.png')
if not ok then
  print('error: ' .. img)
-- else use `img`
end
```

**Comment by jbansal** [comment]
Hi deltheil,
Thank you for solving the issue.

Regards,
Jitendra Bansal
